# Generated by Django 4.2.3 on 2024-02-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=200)),
                ('statut', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
