# Generated by Django 4.2.3 on 2024-02-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('code_depot', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('code_etab', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'depot',
                'managed': True,
            },
        ),
    ]
