# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-17 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('code_article_dem', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('code_barre', models.CharField(max_length=50)),
                ('code_article_gen', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=100)),
                ('code_taille', models.CharField(max_length=50)),
                ('lib_taille', models.CharField(max_length=100)),
                ('code_couleur', models.CharField(max_length=50)),
                ('lib_couleur', models.CharField(max_length=100)),
                ('code_fournisseur', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('code_f', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('libellef', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=100)),
                ('txt_libre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'famille',
                'managed': False,
            },
        ),
    ]
