# Generated by Django 4.2.3 on 2024-02-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('code_article_dem', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('code_barre', models.CharField(blank=True, max_length=50, null=True)),
                ('code_article_gen', models.CharField(blank=True, max_length=50, null=True)),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('code_taille', models.CharField(blank=True, max_length=50, null=True)),
                ('lib_taille', models.CharField(blank=True, max_length=100, null=True)),
                ('code_couleur', models.CharField(blank=True, max_length=50, null=True)),
                ('lib_couleur', models.CharField(blank=True, max_length=100, null=True)),
                ('code_fournisseur', models.CharField(blank=True, max_length=50, null=True)),
                ('fam1', models.CharField(blank=True, max_length=50, null=True)),
                ('fam2', models.CharField(blank=True, max_length=50, null=True)),
                ('fam3', models.CharField(blank=True, max_length=50, null=True)),
                ('fam4', models.CharField(blank=True, max_length=50, null=True)),
                ('fam5', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'article',
                'managed': True,
            },
        ),
    ]
