# Generated by Django 4.2.3 on 2025-06-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('code_article_dem', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('code_barre', models.CharField(blank=True, max_length=50, null=True)),
                ('code_article_gen', models.CharField(blank=True, max_length=50, null=True)),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('code_taille', models.CharField(blank=True, max_length=50, null=True)),
                ('lib_taille', models.CharField(blank=True, max_length=100, null=True)),
                ('code_couleur', models.CharField(blank=True, max_length=50, null=True)),
                ('lib_couleur', models.CharField(blank=True, max_length=100, null=True)),
                ('code_fournisseur', models.CharField(blank=True, max_length=50, null=True)),
                ('fam1', models.CharField(blank=True, max_length=50, null=True)),
                ('fam1_label', models.CharField(blank=True, max_length=100, null=True)),
                ('fam2', models.CharField(blank=True, max_length=50, null=True)),
                ('fam2_label', models.CharField(blank=True, max_length=100, null=True)),
                ('fam3', models.CharField(blank=True, max_length=50, null=True)),
                ('fam3_label', models.CharField(blank=True, max_length=100, null=True)),
                ('fam4', models.CharField(blank=True, max_length=50, null=True)),
                ('fam4_label', models.CharField(blank=True, max_length=100, null=True)),
                ('fam8', models.CharField(blank=True, max_length=50, null=True)),
                ('fam8_label', models.CharField(blank=True, max_length=100, null=True)),
                ('date_injection', models.DateField(blank=True, null=True)),
                ('fournisseur_principale', models.CharField(blank=True, max_length=50, null=True)),
                ('table_libre_9', models.CharField(blank=True, max_length=50, null=True)),
                ('ferme', models.CharField(choices=[('X', 'X'), ('_', '_')], default='_', max_length=1)),
            ],
            options={
                'db_table': 'article',
                'managed': True,
            },
        ),
    ]
