# Generated by Django 4.2.3 on 2025-02-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_fournisseur_principale'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fam1_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='fam2_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='fam3_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='fam4_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='fam5_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='ferme',
            field=models.CharField(choices=[('X', 'X'), ('_', '_')], default='_', max_length=1),
        ),
        migrations.AddField(
            model_name='article',
            name='table_libre_9',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
