# Generated by Django 4.2.3 on 2025-02-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_fam1_label_article_fam2_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='fam5',
            new_name='fam8',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='fam5_label',
            new_name='fam8_label',
        ),
    ]
