version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "AhmedAmine8899"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - db_data:/var/opt/mssql

  web:
    build: .
    command: /usr/src/app/entrypoint.sh  # Custom entrypoint script
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app  # Mount the code volume to access entrypoint script

volumes:
  db_data:
