# Generated by Django 4.2.3 on 2025-06-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ventes', models.DateField()),
                ('code_article', models.CharField(max_length=100)),
                ('code_barre', models.CharField(max_length=50)),
                ('qte', models.IntegerField()),
                ('code_etab', models.CharField(max_length=20)),
                ('num_ticket', models.CharField(max_length=20)),
                ('num_ligne', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ventes',
                'managed': True,
            },
        ),
    ]
