# Generated by Django 4.2.3 on 2024-12-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='code_article',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vente',
            name='qte',
            field=models.IntegerField(),
        ),
    ]
