# Generated by Django 4.2.3 on 2025-01-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_alter_vente_code_article_alter_vente_qte'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='num_ligne',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vente',
            name='num_ticket',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vente',
            unique_together={('num_ticket', 'num_ligne', 'code_etab')},
        ),
    ]
