# Generated by Django 4.2.3 on 2025-01-31 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_vente_num_ligne_vente_num_ticket_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vente',
            unique_together={('num_ticket', 'num_ligne', 'code_etab', 'code_barre')},
        ),
    ]
