# Generated by Django 4.2.3 on 2025-02-01 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0006_alter_vente_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vente',
            unique_together={('num_ticket', 'num_ligne', 'code_etab', 'code_barre', 'qte')},
        ),
    ]
