# Generated by Django 4.2.3 on 2025-02-01 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0007_alter_vente_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vente',
            unique_together=set(),
        ),
    ]
