# Generated by Django 4.2.3 on 2024-02-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('code_etab', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100, null=True)),
                ('adresse1', models.CharField(max_length=200, null=True)),
                ('adresse2', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('priorite', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'etablissement',
                'managed': True,
            },
        ),
    ]
