# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-17 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('code_etab', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('adresse1', models.CharField(max_length=200)),
                ('adresse2', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('priorite', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'etablissement',
                'managed': False,
            },
        ),
    ]
