# Generated by Django 4.2.3 on 2025-02-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='secteur',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
