# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-17 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailleSession',
            fields=[
                ('id_detaille', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stock_physique', models.FloatField()),
                ('stock_min', models.FloatField()),
            ],
            options={
                'db_table': 'detaille_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnteteSession',
            fields=[
                ('code_session', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('critere', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'entete_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('code_prop', models.AutoField(primary_key=True, serialize=False)),
                ('qte_trf', models.FloatField()),
                ('statut', models.CharField(max_length=100)),
                ('etat', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'proposition',
                'managed': False,
            },
        ),
    ]
