# Generated by Django 4.2.3 on 2024-02-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailleSession',
            fields=[
                ('id_detaille', models.AutoField(primary_key=True, serialize=False)),
                ('code_session', models.IntegerField(db_column='code_session')),
                ('code_article_dem', models.CharField(max_length=50)),
                ('code_etab', models.CharField(max_length=50)),
                ('stock_physique', models.FloatField()),
                ('stock_min', models.FloatField()),
            ],
            options={
                'db_table': 'detaille_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('code_prop', models.AutoField(primary_key=True, serialize=False)),
                ('code_detaille_emet', models.IntegerField(db_column='code_detaille_emet')),
                ('code_detaille_recep', models.IntegerField(db_column='code_detaille_recep')),
                ('qte_trf', models.FloatField()),
                ('statut', models.CharField(max_length=100)),
                ('etat', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'proposition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnteteSession',
            fields=[
                ('code_session', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('id_user', models.IntegerField(db_column='id_user')),
                ('critere', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'entete_session',
                'managed': True,
            },
        ),
    ]
