# Generated by Django 4.2.3 on 2024-03-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trf_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaillesession',
            name='code_article_dem',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detaillesession',
            name='code_etab',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
