# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-17 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('code_article_dem', models.ForeignKey(db_column='code_article_dem', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='articles.Article')),
                ('code_etab', models.CharField(max_length=50)),
                ('code_barre', models.CharField(max_length=50)),
                ('stock_min', models.FloatField()),
                ('stock_physique', models.FloatField()),
                ('ventes', models.FloatField()),
                ('trecu', models.IntegerField(db_column='Trecu')),
                ('t_trf_recu', models.IntegerField(db_column='T_trf_recu')),
                ('t_trf_emis', models.IntegerField(db_column='T_trf_emis')),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
    ]
